-- Spells each class learns from its own trainers (names). Built by Claude from your server database.
CleanSpellbook_Class = {
  DRUID = {
    ["Abolish Poison"]=1,["Attacking"]=1,["Barkskin"]=1,["Bash"]=1,["Cat Form"]=1,["Challenging Roar"]=1,
    ["Claw"]=1,["Closing"]=1,["Cower"]=1,["Cultivation"]=1,["Cyclone"]=1,["Dash"]=1,
    ["Demoralizing Roar"]=1,["Detect"]=1,["Dire Bear Form"]=1,["Duel"]=1,["Endurance"]=1,["Enrage"]=1,
    ["Entangling Roots"]=1,["Faerie Fire"]=1,["Faerie Fire (Feral)"]=1,["Feline Grace"]=1,["Ferocious Bite"]=1,["Fetish"]=1,
    ["Flight Form"]=1,["Frenzied Regeneration"]=1,["Gift of the Wild"]=1,["Grovel"]=1,["Healing Touch"]=1,["Hibernate"]=1,
    ["Honorless Target"]=1,["Hurricane"]=1,["Innervate"]=1,["Insect Swarm"]=1,["Lacerate"]=1,["Lifebloom"]=1,
    ["Maim"]=1,["Mangle (Bear)"]=1,["Mangle (Cat)"]=1,["Mark of the Wild"]=1,["Maul"]=1,["Moonfire"]=1,
    ["Nature Resistance"]=1,["Nature's Grasp"]=1,["Opening"]=1,["Opening - No Text"]=1,["Pounce"]=1,["Prowl"]=1,
    ["Quickness"]=1,["Rake"]=1,["Ravage"]=1,["Rebirth"]=1,["Regrowth"]=1,["Rejuvenation"]=1,
    ["Remove Curse"]=1,["Remove Insignia"]=1,["Rip"]=1,["SPELLDEFENSE (DND)"]=1,["Shadowmeld"]=1,["Shadowmeld Passive"]=1,
    ["Shred"]=1,["Soothe Animal"]=1,["Starfire"]=1,["Stuck"]=1,["Summon Friend"]=1,["Swipe"]=1,
    ["Thorns"]=1,["Tiger's Fury"]=1,["Track Humanoids"]=1,["Tranquility"]=1,["Travel Form"]=1,["War Stomp"]=1,
    ["Wisp Spirit"]=1,["Wrath"]=1,
  },
  HUNTER = {
    ["Advantaged State (DND)"]=1,["Aimed Shot"]=1,["Arcane Affinity"]=1,["Arcane Shot"]=1,["Arcane Torrent"]=1,["Aspect of the Beast"]=1,
    ["Aspect of the Cheetah"]=1,["Aspect of the Hawk"]=1,["Aspect of the Monkey"]=1,["Aspect of the Pack"]=1,["Aspect of the Viper"]=1,["Aspect of the Wild"]=1,
    ["Attacking"]=1,["Axe Specialization"]=1,["Beast Lore"]=1,["Beast Slaying"]=1,["Berserking"]=1,["Blood Fury"]=1,
    ["Bow Specialization"]=1,["Closing"]=1,["Command"]=1,["Concussive Shot"]=1,["Counterattack"]=1,["Cultivation"]=1,
    ["Defensive State (DND)"]=1,["Defensive State 2 (DND)"]=1,["Detect"]=1,["Disengage"]=1,["Distracting Shot"]=1,["Duel"]=1,
    ["Eagle Eye"]=1,["Endurance"]=1,["Explosive Trap"]=1,["Eyes of the Beast"]=1,["Feign Death"]=1,["Find Treasure"]=1,
    ["Flare"]=1,["Freezing Trap"]=1,["Frost Resistance"]=1,["Frost Trap"]=1,["Gemcutting"]=1,["Gift of the Naaru"]=1,
    ["Grovel"]=1,["Gun Specialization"]=1,["Hardiness"]=1,["Heroic Presence"]=1,["Honorless Target"]=1,["Hunter's Mark"]=1,
    ["Immolation Trap"]=1,["Kill Command"]=1,["Magic Resistance"]=1,["Mana Tap"]=1,["Mend Pet"]=1,["Misdirection"]=1,
    ["Mongoose Bite"]=1,["Multi-Shot"]=1,["Nature Resistance"]=1,["Opening"]=1,["Opening - No Text"]=1,["Quickness"]=1,
    ["Rapid Fire"]=1,["Raptor Strike"]=1,["Regeneration"]=1,["Remove Insignia"]=1,["SPELLDEFENSE (DND)"]=1,["Scare Beast"]=1,
    ["Scorpid Sting"]=1,["Serpent Sting"]=1,["Shadow Resistance"]=1,["Shadowmeld"]=1,["Shadowmeld Passive"]=1,["Snake Trap"]=1,
    ["Steady Shot"]=1,["Stoneform"]=1,["Stuck"]=1,["Summon Friend"]=1,["Throwing Specialization"]=1,["Track Beasts"]=1,
    ["Track Demons"]=1,["Track Dragonkin"]=1,["Track Elementals"]=1,["Track Giants"]=1,["Track Hidden"]=1,["Track Humanoids"]=1,
    ["Track Undead"]=1,["Tranquilizing Shot"]=1,["Trueshot Aura"]=1,["Viper Sting"]=1,["Volley"]=1,["War Stomp"]=1,
    ["Wing Clip"]=1,["Wisp Spirit"]=1,["Wyvern Sting"]=1,
  },
  MAGE = {
    ["Amplify Magic"]=1,["Arcane Affinity"]=1,["Arcane Blast"]=1,["Arcane Brilliance"]=1,["Arcane Explosion"]=1,["Arcane Intellect"]=1,
    ["Arcane Missiles"]=1,["Arcane Resistance"]=1,["Arcane Torrent"]=1,["Attacking"]=1,["Beast Slaying"]=1,["Berserking"]=1,
    ["Blast Wave"]=1,["Blink"]=1,["Blizzard"]=1,["Bow Specialization"]=1,["Cannibalize"]=1,["Closing"]=1,
    ["Cone of Cold"]=1,["Conjure Food"]=1,["Conjure Mana Agate"]=1,["Conjure Mana Citrine"]=1,["Conjure Mana Emerald"]=1,["Conjure Mana Jade"]=1,
    ["Conjure Mana Ruby"]=1,["Conjure Water"]=1,["Counterspell"]=1,["Dampen Magic"]=1,["Detect"]=1,["Diplomacy"]=1,
    ["Dragon's Breath"]=1,["Duel"]=1,["Engineering Specialization"]=1,["Escape Artist"]=1,["Evocation"]=1,["Expansive Mind"]=1,
    ["Fire Blast"]=1,["Fire Ward"]=1,["Fireball"]=1,["Flamestrike"]=1,["Frost Armor"]=1,["Frost Nova"]=1,
    ["Frost Ward"]=1,["Frostbolt"]=1,["Gemcutting"]=1,["Gift of the Naaru"]=1,["Grovel"]=1,["Honorless Target"]=1,
    ["Ice Armor"]=1,["Ice Barrier"]=1,["Ice Block"]=1,["Ice Lance"]=1,["Inspiring Presence"]=1,["Invisibility"]=1,
    ["Mace Specialization"]=1,["Mage Armor"]=1,["Magic Resistance"]=1,["Mana Shield"]=1,["Mana Tap"]=1,["Molten Armor"]=1,
    ["Opening"]=1,["Opening - No Text"]=1,["Perception"]=1,["Polymorph"]=1,["Portal: Darnassus"]=1,["Portal: Exodar"]=1,
    ["Portal: Ironforge"]=1,["Portal: Orgrimmar"]=1,["Portal: Shattrath"]=1,["Portal: Silvermoon"]=1,["Portal: Stonard"]=1,["Portal: Stormwind"]=1,
    ["Portal: Theramore"]=1,["Portal: Thunder Bluff"]=1,["Portal: Undercity"]=1,["Pyroblast"]=1,["Regeneration"]=1,["Remove Insignia"]=1,
    ["Remove Lesser Curse"]=1,["Ritual of Refreshment"]=1,["SPELLDEFENSE (DND)"]=1,["Scorch"]=1,["Shadow Resistance"]=1,["Slow Fall"]=1,
    ["Spellsteal"]=1,["Stuck"]=1,["Summon Friend"]=1,["Sword Specialization"]=1,["Teleport: Darnassus"]=1,["Teleport: Exodar"]=1,
    ["Teleport: Ironforge"]=1,["Teleport: Orgrimmar"]=1,["Teleport: Shattrath"]=1,["Teleport: Silvermoon"]=1,["Teleport: Stonard"]=1,["Teleport: Stormwind"]=1,
    ["Teleport: Theramore"]=1,["Teleport: Thunder Bluff"]=1,["Teleport: Undercity"]=1,["The Human Spirit"]=1,["Throwing Specialization"]=1,["Underwater Breathing"]=1,
    ["Will of the Forsaken"]=1,
  },
  PALADIN = {
    ["Arcane Affinity"]=1,["Arcane Torrent"]=1,["Attacking"]=1,["Avenger's Shield"]=1,["Avenging Wrath"]=1,["Blessing of Freedom"]=1,
    ["Blessing of Light"]=1,["Blessing of Might"]=1,["Blessing of Protection"]=1,["Blessing of Sacrifice"]=1,["Blessing of Salvation"]=1,["Blessing of Sanctuary"]=1,
    ["Blessing of Wisdom"]=1,["Cleanse"]=1,["Closing"]=1,["Concentration Aura"]=1,["Consecration"]=1,["Crusader Aura"]=1,
    ["Detect"]=1,["Devotion Aura"]=1,["Diplomacy"]=1,["Divine Intervention"]=1,["Divine Protection"]=1,["Divine Shield"]=1,
    ["Duel"]=1,["Exorcism"]=1,["Find Treasure"]=1,["Fire Resistance Aura"]=1,["Flash of Light"]=1,["Frost Resistance"]=1,
    ["Frost Resistance Aura"]=1,["Gemcutting"]=1,["Gift of the Naaru"]=1,["Greater Blessing of Kings"]=1,["Greater Blessing of Light"]=1,["Greater Blessing of Might"]=1,
    ["Greater Blessing of Salvation"]=1,["Greater Blessing of Sanctuary"]=1,["Greater Blessing of Wisdom"]=1,["Grovel"]=1,["Gun Specialization"]=1,["Hammer of Justice"]=1,
    ["Hammer of Wrath"]=1,["Heroic Presence"]=1,["Holy Light"]=1,["Holy Shield"]=1,["Holy Shock"]=1,["Holy Wrath"]=1,
    ["Honorless Target"]=1,["Judgement"]=1,["Lay on Hands"]=1,["Libram"]=1,["Mace Specialization"]=1,["Magic Resistance"]=1,
    ["Mana Tap"]=1,["Opening"]=1,["Opening - No Text"]=1,["Perception"]=1,["Purify"]=1,["Redemption"]=1,
    ["Remove Insignia"]=1,["Retribution Aura"]=1,["Righteous Defense"]=1,["Righteous Fury"]=1,["SPELLDEFENSE (DND)"]=1,["Seal of Blood"]=1,
    ["Seal of Command"]=1,["Seal of Justice"]=1,["Seal of Light"]=1,["Seal of Righteousness"]=1,["Seal of Vengeance"]=1,["Seal of Wisdom"]=1,
    ["Seal of the Crusader"]=1,["Shadow Resistance"]=1,["Shadow Resistance Aura"]=1,["Spiritual Attunement"]=1,["Stoneform"]=1,["Stuck"]=1,
    ["Summon Charger"]=1,["Summon Friend"]=1,["Summon Warhorse"]=1,["Sword Specialization"]=1,["The Human Spirit"]=1,["Turn Evil"]=1,
    ["Turn Undead"]=1,
  },
  PRIEST = {
    ["Abolish Disease"]=1,["Arcane Affinity"]=1,["Arcane Torrent"]=1,["Attacking"]=1,["Beast Slaying"]=1,["Berserking"]=1,
    ["Binding Heal"]=1,["Bow Specialization"]=1,["Cannibalize"]=1,["Chastise"]=1,["Circle of Healing"]=1,["Closing"]=1,
    ["Consume Magic"]=1,["Cure Disease"]=1,["Desperate Prayer"]=1,["Detect"]=1,["Devouring Plague"]=1,["Diplomacy"]=1,
    ["Dispel Magic"]=1,["Divine Spirit"]=1,["Duel"]=1,["Elune's Grace"]=1,["Fade"]=1,["Fear Ward"]=1,
    ["Feedback"]=1,["Find Treasure"]=1,["Flash Heal"]=1,["Frost Resistance"]=1,["Gemcutting"]=1,["Gift of the Naaru"]=1,
    ["Greater Heal"]=1,["Grovel"]=1,["Gun Specialization"]=1,["Heal"]=1,["Hex of Weakness"]=1,["Holy Fire"]=1,
    ["Holy Nova"]=1,["Honorless Target"]=1,["Inner Fire"]=1,["Inspiring Presence"]=1,["Lesser Heal"]=1,["Levitate"]=1,
    ["Lightwell"]=1,["Mace Specialization"]=1,["Magic Resistance"]=1,["Mana Burn"]=1,["Mana Tap"]=1,["Mass Dispel"]=1,
    ["Mind Blast"]=1,["Mind Control"]=1,["Mind Flay"]=1,["Mind Soothe"]=1,["Mind Vision"]=1,["Nature Resistance"]=1,
    ["Opening"]=1,["Opening - No Text"]=1,["Perception"]=1,["Power Word: Fortitude"]=1,["Power Word: Shield"]=1,["Prayer of Fortitude"]=1,
    ["Prayer of Healing"]=1,["Prayer of Mending"]=1,["Prayer of Shadow Protection"]=1,["Prayer of Spirit"]=1,["Psychic Scream"]=1,["Quickness"]=1,
    ["Regeneration"]=1,["Remove Insignia"]=1,["Renew"]=1,["Resurrection"]=1,["SPELLDEFENSE (DND)"]=1,["Shackle Undead"]=1,
    ["Shadow Protection"]=1,["Shadow Resistance"]=1,["Shadow Word: Death"]=1,["Shadow Word: Pain"]=1,["Shadowfiend"]=1,["Shadowguard"]=1,
    ["Shadowmeld"]=1,["Shadowmeld Passive"]=1,["Smite"]=1,["Starshards"]=1,["Stoneform"]=1,["Stuck"]=1,
    ["Summon Friend"]=1,["Sword Specialization"]=1,["Symbol of Hope"]=1,["The Human Spirit"]=1,["Throwing Specialization"]=1,["Touch of Weakness"]=1,
    ["Underwater Breathing"]=1,["Vampiric Touch"]=1,["Will of the Forsaken"]=1,["Wisp Spirit"]=1,
  },
  ROGUE = {
    ["Ambush"]=1,["Anesthetic Poison"]=1,["Arcane Affinity"]=1,["Arcane Resistance"]=1,["Arcane Torrent"]=1,["Attacking"]=1,
    ["Axe Specialization"]=1,["Backstab"]=1,["Beast Slaying"]=1,["Berserking"]=1,["Blind"]=1,["Blood Fury"]=1,
    ["Bow Specialization"]=1,["Cannibalize"]=1,["Cheap Shot"]=1,["Cloak of Shadows"]=1,["Closing"]=1,["Command"]=1,
    ["Crippling Poison"]=1,["Crippling Poison II"]=1,["Deadly Poison"]=1,["Deadly Poison II"]=1,["Deadly Poison III"]=1,["Deadly Poison IV"]=1,
    ["Deadly Poison V"]=1,["Deadly Poison VI"]=1,["Deadly Poison VII"]=1,["Deadly Throw"]=1,["Defensive State (DND)"]=1,["Detect"]=1,
    ["Detect Traps"]=1,["Diplomacy"]=1,["Disarm Trap"]=1,["Distract"]=1,["Duel"]=1,["Engineering Specialization"]=1,
    ["Envenom"]=1,["Escape Artist"]=1,["Evasion"]=1,["Eviscerate"]=1,["Expansive Mind"]=1,["Expose Armor"]=1,
    ["Feint"]=1,["Find Treasure"]=1,["Frost Resistance"]=1,["Garrote"]=1,["Gouge"]=1,["Grovel"]=1,
    ["Gun Specialization"]=1,["Hardiness"]=1,["Hemorrhage"]=1,["Honorless Target"]=1,["Instant Poison II"]=1,["Instant Poison III"]=1,
    ["Instant Poison IV"]=1,["Instant Poison V"]=1,["Instant Poison VI"]=1,["Instant Poison VII"]=1,["Kick"]=1,["Kidney Shot"]=1,
    ["Mace Specialization"]=1,["Magic Resistance"]=1,["Mana Tap"]=1,["Mind-numbing Poison"]=1,["Mind-numbing Poison II"]=1,["Mind-numbing Poison III"]=1,
    ["Mutilate"]=1,["Nature Resistance"]=1,["Opening"]=1,["Opening - No Text"]=1,["Perception"]=1,["Pick Lock"]=1,
    ["Pick Pocket"]=1,["Quickness"]=1,["Regeneration"]=1,["Remove Insignia"]=1,["Rogue Passive (DND)"]=1,["Rupture"]=1,
    ["SPELLDEFENSE (DND)"]=1,["Safe Fall"]=1,["Sap"]=1,["Shadow Resistance"]=1,["Shadowmeld"]=1,["Shadowmeld Passive"]=1,
    ["Shiv"]=1,["Sinister Strike"]=1,["Slice and Dice"]=1,["Sprint"]=1,["Stealth"]=1,["Stoneform"]=1,
    ["Stuck"]=1,["Summon Friend"]=1,["Sword Specialization"]=1,["The Human Spirit"]=1,["Throwing Specialization"]=1,["Underwater Breathing"]=1,
    ["Vanish"]=1,["Will of the Forsaken"]=1,["Wisp Spirit"]=1,["Wound Poison"]=1,["Wound Poison II"]=1,["Wound Poison III"]=1,
    ["Wound Poison IV"]=1,["Wound Poison V"]=1,
  },
  SHAMAN = {
    ["Ancestral Spirit"]=1,["Astral Recall"]=1,["Attacking"]=1,["Axe Specialization"]=1,["Beast Slaying"]=1,["Berserking"]=1,
    ["Blood Fury"]=1,["Bloodlust"]=1,["Bow Specialization"]=1,["Chain Heal"]=1,["Chain Lightning"]=1,["Closing"]=1,
    ["Command"]=1,["Cultivation"]=1,["Cure Disease"]=1,["Cure Poison"]=1,["Detect"]=1,["Disease Cleansing Totem"]=1,
    ["Duel"]=1,["Earth Elemental Totem"]=1,["Earth Shield"]=1,["Earth Shock"]=1,["Earthbind Totem"]=1,["Endurance"]=1,
    ["Far Sight"]=1,["Fire Elemental Totem"]=1,["Fire Nova Totem"]=1,["Fire Resistance Totem"]=1,["Flame Shock"]=1,["Flametongue Totem"]=1,
    ["Flametongue Weapon"]=1,["Frost Resistance Totem"]=1,["Frost Shock"]=1,["Frostbrand Weapon"]=1,["Gemcutting"]=1,["Ghost Wolf"]=1,
    ["Gift of the Naaru"]=1,["Grace of Air Totem"]=1,["Grounding Totem"]=1,["Grovel"]=1,["Hardiness"]=1,["Healing Stream Totem"]=1,
    ["Healing Wave"]=1,["Heroism"]=1,["Honorless Target"]=1,["Inspiring Presence"]=1,["Lesser Healing Wave"]=1,["Lightning Bolt"]=1,
    ["Lightning Shield"]=1,["Magma Totem"]=1,["Mana Spring Totem"]=1,["Nature Resistance"]=1,["Nature Resistance Totem"]=1,["Opening"]=1,
    ["Opening - No Text"]=1,["Poison Cleansing Totem"]=1,["Purge"]=1,["Regeneration"]=1,["Reincarnation"]=1,["Remove Insignia"]=1,
    ["Rockbiter Weapon"]=1,["SPELLDEFENSE (DND)"]=1,["Searing Totem"]=1,["Sentry Totem"]=1,["Shadow Resistance"]=1,["Stoneclaw Totem"]=1,
    ["Stoneskin Totem"]=1,["Strength of Earth Totem"]=1,["Stuck"]=1,["Summon Friend"]=1,["Throwing Specialization"]=1,["Totem"]=1,
    ["Totemic Call"]=1,["Tranquil Air Totem"]=1,["Tremor Totem"]=1,["War Stomp"]=1,["Water Breathing"]=1,["Water Shield"]=1,
    ["Water Walking"]=1,["Windfury Totem"]=1,["Windfury Weapon"]=1,["Windwall Totem"]=1,["Wrath of Air Totem"]=1,
  },
  WARLOCK = {
    ["Arcane Affinity"]=1,["Arcane Resistance"]=1,["Arcane Torrent"]=1,["Attacking"]=1,["Axe Specialization"]=1,["Banish"]=1,
    ["Blood Fury"]=1,["Cannibalize"]=1,["Closing"]=1,["Command"]=1,["Conflagrate"]=1,["Corruption"]=1,
    ["Create Firestone"]=1,["Create Healthstone"]=1,["Create Soulstone"]=1,["Create Spellstone"]=1,["Curse of Agony"]=1,["Curse of Doom"]=1,
    ["Curse of Recklessness"]=1,["Curse of Tongues"]=1,["Curse of Weakness"]=1,["Curse of the Elements"]=1,["Dark Pact"]=1,["Death Coil"]=1,
    ["Demon Armor"]=1,["Demon Skin"]=1,["Detect"]=1,["Detect Invisibility"]=1,["Diplomacy"]=1,["Drain Life"]=1,
    ["Drain Mana"]=1,["Drain Soul"]=1,["Duel"]=1,["Engineering Specialization"]=1,["Enslave Demon"]=1,["Escape Artist"]=1,
    ["Expansive Mind"]=1,["Eye of Kilrogg"]=1,["Fear"]=1,["Fel Armor"]=1,["Grovel"]=1,["Hardiness"]=1,
    ["Health Funnel"]=1,["Hellfire"]=1,["Honorless Target"]=1,["Howl of Terror"]=1,["Immolate"]=1,["Incinerate"]=1,
    ["Life Tap"]=1,["Mace Specialization"]=1,["Magic Resistance"]=1,["Mana Tap"]=1,["Opening"]=1,["Opening - No Text"]=1,
    ["Perception"]=1,["Rain of Fire"]=1,["Remove Insignia"]=1,["Ritual of Souls"]=1,["Ritual of Summoning"]=1,["SPELLDEFENSE (DND)"]=1,
    ["Searing Pain"]=1,["Seed of Corruption"]=1,["Sense Demons"]=1,["Shadow Bolt"]=1,["Shadow Resistance"]=1,["Shadow Ward"]=1,
    ["Shadowburn"]=1,["Shadowfury"]=1,["Siphon Life"]=1,["Soul Fire"]=1,["Soulshatter"]=1,["Stuck"]=1,
    ["Summon Felsteed"]=1,["Summon Friend"]=1,["Sword Specialization"]=1,["Teach Summon Dreadsteed"]=1,["The Human Spirit"]=1,["Underwater Breathing"]=1,
    ["Unending Breath"]=1,["Unstable Affliction"]=1,["Will of the Forsaken"]=1,
  },
  WARRIOR = {
    ["Arcane Resistance"]=1,["Attacking"]=1,["Axe Specialization"]=1,["Battle Shout"]=1,["Battle Stance"]=1,["Beast Slaying"]=1,
    ["Berserker Rage"]=1,["Berserking"]=1,["Blood Fury"]=1,["Bloodrage"]=1,["Bloodthirst"]=1,["Bow Specialization"]=1,
    ["Cannibalize"]=1,["Challenging Shout"]=1,["Charge"]=1,["Cleave"]=1,["Closing"]=1,["Command"]=1,
    ["Commanding Shout"]=1,["Cultivation"]=1,["Defensive State (DND)"]=1,["Demoralizing Shout"]=1,["Detect"]=1,["Devastate"]=1,
    ["Diplomacy"]=1,["Disarm"]=1,["Duel"]=1,["Endurance"]=1,["Engineering Specialization"]=1,["Escape Artist"]=1,
    ["Execute"]=1,["Expansive Mind"]=1,["Find Treasure"]=1,["Frost Resistance"]=1,["Gemcutting"]=1,["Gift of the Naaru"]=1,
    ["Grovel"]=1,["Gun Specialization"]=1,["Hamstring"]=1,["Hardiness"]=1,["Heroic Presence"]=1,["Heroic Strike"]=1,
    ["Honorless Target"]=1,["Intercept"]=1,["Intervene"]=1,["Intimidating Shout"]=1,["Mace Specialization"]=1,["Mocking Blow"]=1,
    ["Mortal Strike"]=1,["Nature Resistance"]=1,["Opening"]=1,["Opening - No Text"]=1,["Overpower"]=1,["Perception"]=1,
    ["Pummel"]=1,["Quickness"]=1,["Rampage"]=1,["Recklessness"]=1,["Regeneration"]=1,["Remove Insignia"]=1,
    ["Rend"]=1,["Retaliation"]=1,["Revenge"]=1,["SPELLDEFENSE (DND)"]=1,["Shadow Resistance"]=1,["Shadowmeld"]=1,
    ["Shadowmeld Passive"]=1,["Shield Bash"]=1,["Shield Block"]=1,["Shield Slam"]=1,["Shield Wall"]=1,["Slam"]=1,
    ["Spell Reflection"]=1,["Stance Mastery"]=1,["Stoneform"]=1,["Stuck"]=1,["Summon Friend"]=1,["Sunder Armor"]=1,
    ["Sword Specialization"]=1,["The Human Spirit"]=1,["Throwing Specialization"]=1,["Thunder Clap"]=1,["Underwater Breathing"]=1,["Victorious State"]=1,
    ["Victory Rush"]=1,["War Stomp"]=1,["Whirlwind"]=1,["Will of the Forsaken"]=1,["Wisp Spirit"]=1,
  },
}
